language: cpp

services:
  - docker

matrix:
  include:
    - env: CXX=g++-9

before_install:
  - docker pull ubuntu:focal

script:
  - chmod +x build.sh
  - docker run --name build --rm -idt ubuntu /bin/bash
  - docker exec build build.sh
