language: cpp

services:
  - docker

matrix:
  include:
    - env: CXX=g++-9

before_install:
  - docker pull ubuntu:focal

script:
  - git clone https://github.com/SCOTT-HAMILTON/ControlsForFake-gtk
  - docker container ls
  - docker cp ControlsForFake-gtk ubuntu:/ControlsForFake-gtk
  - docker run ubuntu /bin/sh -c "chmod +x ControlsForFake-gtk/build.sh && ./ControlsForFake-gtk/build.sh"
