language: cpp

sudo: required
dist: bionic

compiler:
  - gcc
  - clang

os:
  - linux

addons:
  apt:
    update: true
    packages:
      - libgtkmm-3.0-dev

install:
  - sudo python3 -m pip install meson
  - git clone https://github.com/SCOTT-HAMILTON/FakeLib
  - cd FakeLib
  - mkdir build
  - meson build
  - ninja -C build
  - sudo ninja -C build install
  - cd ..
  - git clone https://github.com/p-ranav/argparse
  - cd argparse
  - mkdir build
  - cd build
  - cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DARGPARSE_BUILD_TESTS=OFF ..
  - cd ..
  - ninja -C build
  - sudo ninja -C build install
  - cd ..
  - git clone https://github.com/SCOTT-HAMILTON/FakeMicWavPlayer
  - cd FakeMicWavPlayer
  - mkdir build
  - meson build
  - ninja -C build
  - sudo ninja -C build install
  - cd ..

script:
  - mkdir build
  - meson build
  - ninja -C build

