dist: bionic
group: travis_latest

os: linux
language: python

addons:
  apt:
    sources:
    - llvm-toolchain-bionic-10
    - ubuntu-toolchain-r-test
    packages:
    - gcc-9
    - cmake
    - ninja-build
    - libstdc++-8-dev
    - 
    update: true

matrix:
  include:
    - env: CXX=g++-9
before_install:
# Moving to GCC
  - sudo apt-get -qq update
  - sudo apt-get install g++-9
  - sudo apt-get install libgtkmm-3.0-dev
  - sudo apt-get install libpulse-dev libogg-dev libvorbis-dev python3-pip python3-setuptools

install:
  - sudo python3 -m pip install meson
  - git clone https://github.com/SCOTT-HAMILTON/FakeLib
  - cd FakeLib
  - mkdir build
  - meson build
  - ninja -C build
  - sudo ninja -C build install
  - cd ..
  - git clone https://github.com/p-ranav/argparse
  - cd argparse
  - mkdir build
  - cd build
  - cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DARGPARSE_BUILD_TESTS=OFF ..
  - cd ..
  - ninja -C build
  - sudo ninja -C build install
  - cd ..
  - git clone https://github.com/SCOTT-HAMILTON/FakeMicWavPlayer
  - cd FakeMicWavPlayer
  - mkdir build
  - meson build
  - ninja -C build
  - sudo ninja -C build install
  - cd ..

script:
  - mkdir build
  - meson build --verbose
  - ninja -C build

