language: cpp

services:
  - docker

matrix:
  include:
    - env: CXX=g++-9
    - env: CXX=clang++-10

before_install:
  - docker pull ubuntu:focal

script:
  - chmod +x build.sh
  - echo $CXX
  - docker run -d -e "CXX=$CXX" --name build --rm -it ubuntu /bin/bash
  - docker cp build.sh build:/build.sh
  - docker exec build ./build.sh
